- Updates to conditionally install pwsh based on platform

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -16,8 +16,7 @@ FROM python:${PYTHON_VERSION}
 RUN python --version
 
 # Install Node.js
-# Looks like wget, gnupg and apt-transport-https are already available in the base image
-RUN apt-get update && apt-get install -y curl
+RUN apt-get update && apt-get install -y curl wget apt-transport-https software-properties-common
 RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
 RUN apt-get install -y nodejs
 
@@ -25,77 +24,49 @@ RUN apt-get install -y nodejs
 RUN node --version
 RUN npm --version || echo "npm installation failed"
 
-# Install PowerShelL
-# Bug Fix: Had to declare the ARG PWSH_VERSION again here to use it in the RUN command!!
-ARG ARCH
-ARG PLATFORM
-RUN if [ "$PLATFORM" = "linux/arm64" ]; then \
-      ARCH="linux-arm64"; \
-    else \
-      ARCH="linux-x64"; \
-    fi \
-    && echo "PLATFORM: $PLATFORM" \
-    && sleep 10 \
-    && echo "Architecture: $ARCH" \
-    && sleep 10
+# Conditionally install PowerShell based on the platform
+# Bug Fix: Had to declare the ARG PWSH_VERSION again here to use it in the RUN command!
 ARG PWSH_VERSION
-# RUN apt-get install -y wget \
-    # && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-x64.tar.gz \
-    # && mkdir pwsh-${PWSH_VERSION} \
-    # && tar -xvf powershell-${PWSH_VERSION}-linux-x64.tar.gz -C pwsh-${PWSH_VERSION} \
-    # && rm powershell-${PWSH_VERSION}-linux-x64.tar.gz \
-    # && mv pwsh-${PWSH_VERSION} /usr/local/bin/pwsh${PWSH_VERSION} \
-    # && ln -s /usr/local/bin/pwsh${PWSH_VERSION}/pwsh /usr/bin/pwsh \
-    # && chmod +x /usr/bin/pwsh \
-    # # libicu is required for PowerShell; alternatively: export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
-    # && apt-get install -y libicu-dev \
-    # # Verify that PowerShell was installed correctly
-    # && pwsh --version || echo "PowerShell installation failed"
-    
-    # # PowerShell v7.4.2 is not available for Debian 12 (Bookworm) as of 2024-04-20 for arm64
+ARG PLATFORM
+RUN if [ "$PLATFORM" = "linux/amd64" ]; then \
+      wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
+      && dpkg -i packages-microsoft-prod.deb \
+      && apt-get update \
+      # && apt-get install -y powershell=${PWSH_VERSION}-1.deb \ # If a specific version is needed
+      && apt-get install -y powershell \
+      && apt-get clean \
+      && rm -rf /var/lib/apt/lists/*; \
+    elif [ "$PLATFORM" = "linux/arm64" ]; then \
+        wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-arm64.tar.gz \
+        && mkdir pwsh-${PWSH_VERSION} \
+        && tar -xvf powershell-${PWSH_VERSION}-linux-arm64.tar.gz -C pwsh-${PWSH_VERSION} \
+        && rm powershell-${PWSH_VERSION}-linux-arm64.tar.gz \
+        && mv pwsh-${PWSH_VERSION} /usr/local/bin/pwsh${PWSH_VERSION} \
+        && ln -s /usr/local/bin/pwsh${PWSH_VERSION}/pwsh /usr/bin/pwsh \
+        && chmod +x /usr/bin/pwsh \
+        # libicu is required for PowerShell; alternatively: export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
+        && apt-get install -y libicu-dev \
+        # Verify that PowerShell was installed correctly
+        && echo "PWSH_VERSION: $PWSH_VERSION" \
+        && pwsh --version || echo "PowerShell installation failed" \
+        && sleep 10; \
+    else \
+      echo "PowerShell is not supported on $PLATFORM" \
+      && sleep 20 \
+      && exit 1; \
+    fi
 
-# RUN apt-get update && apt-get install -y wget apt-transport-https software-properties-common \
-#     && wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
-#     && dpkg -i packages-microsoft-prod.deb \
-#     && apt-get update \
-#     && apt-get install -y powershell=${PWSH_VERSION}-1.deb \
-#     && apt-get clean \
-#     && rm -rf /var/lib/apt/lists/*
-
-RUN apt-get update && apt-get install -y wget apt-transport-https software-properties-common \
-    && wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
-    && dpkg -i packages-microsoft-prod.deb \
-    && apt-get update \
-    && apt-get install -y powershell \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/*
-
-# # Conditionally install PowerShell based on the platform
+# ARG ARCH
 # ARG PLATFORM
-# RUN if [ "$PLATFORM" = "linux/amd64" ]; then \
-#       wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
-#       && dpkg -i packages-microsoft-prod.deb \
-#       && apt-get update \
-#       # && apt-get install -y powershell=${PWSH_VERSION}-1.deb \
-#       && apt-get install -y powershell \
-#       && apt-get clean \
-#       && rm -rf /var/lib/apt/lists/*; \
+# RUN if [ "$PLATFORM" = "linux/arm64" ]; then \
+#       ARCH="linux-arm64"; \
 #     else \
-#       echo "PowerShell is not supported on $PLATFORM" \
-#       && sleep 20 \
-#       && exit 1; \
-#     fi
-
-    # # Another way tried...
-    # && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell_${PWSH_VERSION}-1.deb_amd64.deb \
-    # Register the Microsoft repository GPG keys
-    # && dpkg -i powershell_${PWSH_VERSION}-1.deb_amd64.deb \
-    # Update the package list after adding packages.microsoft.com
-    # && apt-get update \
-    # Finally, install PowerShell
-    # && apt-get install -y powershell
-    # && apt-get install -f
-# RUN curl -fsSL https://aka.ms/install-powershell.sh | bash -
+#       ARCH="linux-x64"; \
+#     fi \
+#     && echo "PLATFORM: $PLATFORM" \
+#     && sleep 10 \
+#     && echo "Architecture: $ARCH" \
+#     && sleep 10
 
 # Set the working directory in the container to /app
 WORKDIR /app
