- docker-compose.yml: Removes version attribute - README.md: Adds detailed instructions - devcontainer.json: Adds PWSH_VERSION argument and adds vscode-json extension - Dockerfile: Adds arguments for Python, NodeJs, Pwsh versions; grants execute permission on pwsh - requirements.txt: Adds matplotlib and latest version for all packages - *.json: 'Beautified' .json files using vscode-json extension

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,45 +1,64 @@
-# Start from a latest Python 3 base image (3.12.3 as of 2024-04-20)
-# 3-slim-bookworm uses latest Debian 12 (Bookworm) slim image and isn't supported by PowerShell v7.4.2 yet as of 2024-04-20
+# Start from a latest Python 3 base image (3.12.5 as of 2024.09.09 | 3.12.3 as of 2024-04-20)
+# 3-slim-bookworm uses latest Debian 12 (Bookworm) slim image and arm64 flavor isn't supported by PowerShell v7.4.2 yet as of 2024-04-20
 # Visual Studio Code: Cmd + Shift + P -> Dev Containers: Reopen in Container
 # docker ps -all # run this on host
-FROM python:3-slim-bookworm
+
+# Use build arguments for flexibility
+ARG PYTHON_VERSION="3-slim-bookworm"
+ARG NODE_VERSION="20"
+ARG PWSH_VERSION="7.4.2"
+
+# Start from the specified Python base image
+FROM python:${PYTHON_VERSION}
+
+# Verify Python version
+RUN python --version
 
 # Install Node.js
-# Looks like gnupg and apt-transport-https are already available in the base image
+# Looks like wget, gnupg and apt-transport-https are already available in the base image
 RUN apt-get update && apt-get install -y curl
-RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
+RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
 RUN apt-get install -y nodejs
 
-# # Install PowerShell
+# Verify that Node.js and npm were installed correctly
+RUN node --version
+RUN npm --version || echo "npm installation failed"
+
+# Install PowerShelL
+# Bug Fix: Had to declare the ARG PWSH_VERSION again here to use it in the RUN command!!
+ARG PWSH_VERSION
 RUN apt-get install -y wget \
-    && wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell-7.4.2-linux-arm64.tar.gz \
-    && mkdir pwsh-7.4.2 \
-    && tar -xvf powershell-7.4.2-linux-arm64.tar.gz -C pwsh-7.4.2 \
-    && rm powershell-7.4.2-linux-arm64.tar.gz \
-    && mv pwsh-7.4.2 /usr/local/bin/pwsh7.4.2 \
-    && ln -s /usr/local/bin/pwsh7.4.2/pwsh /usr/bin/pwsh \
+    && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-arm64.tar.gz \
+    && mkdir pwsh-${PWSH_VERSION} \
+    && tar -xvf powershell-${PWSH_VERSION}-linux-arm64.tar.gz -C pwsh-${PWSH_VERSION} \
+    && rm powershell-${PWSH_VERSION}-linux-arm64.tar.gz \
+    && mv pwsh-${PWSH_VERSION} /usr/local/bin/pwsh${PWSH_VERSION} \
+    && ln -s /usr/local/bin/pwsh${PWSH_VERSION}/pwsh /usr/bin/pwsh \
+    && chmod +x /usr/bin/pwsh \
     # libicu is required for PowerShell; alternatively: export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
     && apt-get install -y libicu-dev \
     # Verify that PowerShell was installed correctly
-    && pwsh --version
+    && pwsh --version || echo "PowerShell installation failed"
     
-    # PowerShell v7.4.2 is not available for Debian 12 (Bookworm) as of 2024-04-20 for arm64
-    # && wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb \
+    # # PowerShell v7.4.2 is not available for Debian 12 (Bookworm) as of 2024-04-20 for arm64
+    # software-properties-common \
+    # && wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
+    # && dpkg -i packages-microsoft-prod.deb \
+    # && apt-get update \
+    # && apt-get install -y powershell=7.4.5-1.deb11 \
+    # && apt-get clean \
+    # && rm -rf /var/lib/apt/lists/*
+
+    # # Another way tried...
+    # && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell_${PWSH_VERSION}-1.deb_amd64.deb \
     # Register the Microsoft repository GPG keys
-    # && dpkg -i powershell_7.4.2-1.deb_amd64.deb \
+    # && dpkg -i powershell_${PWSH_VERSION}-1.deb_amd64.deb \
     # Update the package list after adding packages.microsoft.com
     # && apt-get update \
     # Finally, install PowerShell
     # && apt-get install -y powershell
     # && apt-get install -f
 # RUN curl -fsSL https://aka.ms/install-powershell.sh | bash -
-
-# Verify that Node.js and npm were installed correctly
-RUN node --version
-RUN npm --version
-
-# Verify that Python was installed correctly
-RUN python --version
 
 # Set the working directory in the container to /app
 WORKDIR /app
@@ -49,3 +68,6 @@ ADD . /app
 
 # Install any needed packages specified in requirements.txt
 RUN pip install --no-cache-dir -r api/requirements.txt
+
+# Set PowerShell as the default shell
+CMD ["pwsh"]
