- Updates it to make it to work for both linux/amd64 and linux/arm64 platforms

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -6,7 +6,8 @@
 # Use build arguments for flexibility
 ARG PYTHON_VERSION="3-slim-bookworm"
 ARG NODE_VERSION="20"
-ARG PWSH_VERSION="7.4.2"
+ARG PWSH_VERSION="7.4.5"
+ARG PLATFORM="linux/arm64"
 
 # Start from the specified Python base image
 FROM python:${PYTHON_VERSION}
@@ -26,28 +27,64 @@ RUN npm --version || echo "npm installation failed"
 
 # Install PowerShelL
 # Bug Fix: Had to declare the ARG PWSH_VERSION again here to use it in the RUN command!!
+ARG ARCH
+ARG PLATFORM
+RUN if [ "$PLATFORM" = "linux/arm64" ]; then \
+      ARCH="linux-arm64"; \
+    else \
+      ARCH="linux-x64"; \
+    fi \
+    && echo "PLATFORM: $PLATFORM" \
+    && sleep 10 \
+    && echo "Architecture: $ARCH" \
+    && sleep 10
 ARG PWSH_VERSION
-RUN apt-get install -y wget \
-    && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-arm64.tar.gz \
-    && mkdir pwsh-${PWSH_VERSION} \
-    && tar -xvf powershell-${PWSH_VERSION}-linux-arm64.tar.gz -C pwsh-${PWSH_VERSION} \
-    && rm powershell-${PWSH_VERSION}-linux-arm64.tar.gz \
-    && mv pwsh-${PWSH_VERSION} /usr/local/bin/pwsh${PWSH_VERSION} \
-    && ln -s /usr/local/bin/pwsh${PWSH_VERSION}/pwsh /usr/bin/pwsh \
-    && chmod +x /usr/bin/pwsh \
-    # libicu is required for PowerShell; alternatively: export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
-    && apt-get install -y libicu-dev \
-    # Verify that PowerShell was installed correctly
-    && pwsh --version || echo "PowerShell installation failed"
+# RUN apt-get install -y wget \
+    # && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-linux-x64.tar.gz \
+    # && mkdir pwsh-${PWSH_VERSION} \
+    # && tar -xvf powershell-${PWSH_VERSION}-linux-x64.tar.gz -C pwsh-${PWSH_VERSION} \
+    # && rm powershell-${PWSH_VERSION}-linux-x64.tar.gz \
+    # && mv pwsh-${PWSH_VERSION} /usr/local/bin/pwsh${PWSH_VERSION} \
+    # && ln -s /usr/local/bin/pwsh${PWSH_VERSION}/pwsh /usr/bin/pwsh \
+    # && chmod +x /usr/bin/pwsh \
+    # # libicu is required for PowerShell; alternatively: export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
+    # && apt-get install -y libicu-dev \
+    # # Verify that PowerShell was installed correctly
+    # && pwsh --version || echo "PowerShell installation failed"
     
     # # PowerShell v7.4.2 is not available for Debian 12 (Bookworm) as of 2024-04-20 for arm64
-    # software-properties-common \
-    # && wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
-    # && dpkg -i packages-microsoft-prod.deb \
-    # && apt-get update \
-    # && apt-get install -y powershell=7.4.5-1.deb11 \
-    # && apt-get clean \
-    # && rm -rf /var/lib/apt/lists/*
+
+# RUN apt-get update && apt-get install -y wget apt-transport-https software-properties-common \
+#     && wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
+#     && dpkg -i packages-microsoft-prod.deb \
+#     && apt-get update \
+#     && apt-get install -y powershell=${PWSH_VERSION}-1.deb \
+#     && apt-get clean \
+#     && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y wget apt-transport-https software-properties-common \
+    && wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
+    && dpkg -i packages-microsoft-prod.deb \
+    && apt-get update \
+    && apt-get install -y powershell \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/*
+
+# # Conditionally install PowerShell based on the platform
+# ARG PLATFORM
+# RUN if [ "$PLATFORM" = "linux/amd64" ]; then \
+#       wget -q "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb" \
+#       && dpkg -i packages-microsoft-prod.deb \
+#       && apt-get update \
+#       # && apt-get install -y powershell=${PWSH_VERSION}-1.deb \
+#       && apt-get install -y powershell \
+#       && apt-get clean \
+#       && rm -rf /var/lib/apt/lists/*; \
+#     else \
+#       echo "PowerShell is not supported on $PLATFORM" \
+#       && sleep 20 \
+#       && exit 1; \
+#     fi
 
     # # Another way tried...
     # && wget https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell_${PWSH_VERSION}-1.deb_amd64.deb \
@@ -68,6 +105,3 @@ ADD . /app
 
 # Install any needed packages specified in requirements.txt
 RUN pip install --no-cache-dir -r api/requirements.txt
-
-# Set PowerShell as the default shell
-CMD ["pwsh"]
